import {
  Folder,
  FolderOpen,
  Briefcase,
  House,
  Building2,
  Store,
  Factory,
  Warehouse,
  Code,
  Terminal,
  Cpu,
  Database,
  Server,
  Cloud,
  Globe,
  Wifi,
  HardDrive,
  Bot,
  Brain,
  Rocket,
  Target,
  Flag,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChartArea,
  TrendingUp,
  Activity,
  Calculator,
  Scale,
  Banknote,
  Wallet,
  CreditCard,
  Receipt,
  Coins,
  Euro,
  File,
  FileText,
  Notebook,
  BookOpen,
  Scroll,
  ClipboardList,
  ListChecks,
  Table2,
  LayoutGrid,
  Layers,
  Sticker,
  Stamp,
  Package,
  Boxes,
  ShoppingCart,
  ShoppingBag,
  Truck,
  Plane,
  Ship,
  Anchor,
  Calendar,
  Clock,
  Timer,
  AlarmClock,
  Bell,
  Mail,
  Send,
  MessageSquare,
  Phone,
  Users,
  User,
  Handshake,
  GraduationCap,
  Languages,
  Crown,
  Award,
  Camera,
  Image,
  Video,
  Film,
  Music,
  Mic,
  Palette,
  Brush,
  Paintbrush,
  PenTool,
  Pencil,
  Type,
  Scissors,
  Ruler,
  Highlighter,
  Wrench,
  Hammer,
  Settings,
  Cog,
  SlidersHorizontal,
  Funnel,
  Search,
  Shield,
  Lock,
  Key,
  Zap,
  Lightbulb,
  Flame,
  Sparkles,
  Star,
  Heart,
  Bookmark,
  Tag,
  Gift,
  Trophy,
  Gem,
  PartyPopper,
  Ticket,
  Percent,
  Atom,
  FlaskConical,
  Microscope,
  Stethoscope,
  Pill,
  Dumbbell,
  Bug,
  Eye,
  Coffee,
  Utensils,
  Pizza,
  Cake,
  Cookie,
  Popcorn,
  Apple,
  Grape,
  Leaf,
  Sprout,
  Trees,
  Flower2,
  Sun,
  Moon,
  CloudRain,
  Snowflake,
  Mountain,
  Dog,
  Cat,
  Bird,
  Fish,
  Rabbit,
  PawPrint,
  Monitor,
  Laptop,
  Smartphone,
  Tv,
  Printer,
  Keyboard,
  Watch,
  Gamepad2,
  Puzzle,
  Blocks,
  Hash,
  AtSign,
  Map as MapIcon,
  MapPin,
  Compass,
} from "lucide-react";

// Icona di default per i progetti senza icona assegnata
export const DEFAULT_PROJECT_ICON = "folder";

/**
 * Set curato di icone lucide utilizzabili come icona di un progetto.
 * `k` = parole chiave (separate da spazio) usate per la ricerca nel picker.
 */
export const PROJECT_ICONS = [
  { key: "folder", Icon: Folder, k: "cartella progetto generico default" },
  { key: "folder-open", Icon: FolderOpen, k: "cartella aperta file" },
  { key: "briefcase", Icon: Briefcase, k: "lavoro azienda ufficio business" },
  { key: "house", Icon: House, k: "casa home abitazione" },
  { key: "building", Icon: Building2, k: "edificio azienda societa palazzo" },
  { key: "store", Icon: Store, k: "negozio vendita commercio shop" },
  { key: "factory", Icon: Factory, k: "fabbrica industria produzione" },
  { key: "warehouse", Icon: Warehouse, k: "magazzino deposito stoccaggio" },
  { key: "code", Icon: Code, k: "codice sviluppo programmazione dev" },
  { key: "terminal", Icon: Terminal, k: "terminale shell console dev" },
  { key: "cpu", Icon: Cpu, k: "cpu processore hardware chip" },
  { key: "database", Icon: Database, k: "database db dati archivio" },
  { key: "server", Icon: Server, k: "server hosting infrastruttura" },
  { key: "cloud", Icon: Cloud, k: "cloud nuvola servizi" },
  { key: "globe", Icon: Globe, k: "web mondo internet globo" },
  { key: "wifi", Icon: Wifi, k: "wifi rete connessione" },
  { key: "hard-drive", Icon: HardDrive, k: "disco storage memoria" },
  { key: "bot", Icon: Bot, k: "bot ai intelligenza artificiale robot" },
  { key: "brain", Icon: Brain, k: "cervello idea ai pensiero" },
  { key: "rocket", Icon: Rocket, k: "razzo lancio startup velocita" },
  { key: "target", Icon: Target, k: "obiettivo target goal" },
  { key: "flag", Icon: Flag, k: "bandiera traguardo obiettivo" },
  { key: "chart-column", Icon: ChartColumn, k: "grafico statistiche analisi barre" },
  { key: "chart-line", Icon: ChartLine, k: "grafico andamento trend linee" },
  { key: "chart-pie", Icon: ChartPie, k: "grafico torta percentuali" },
  { key: "chart-area", Icon: ChartArea, k: "grafico area trend" },
  { key: "trending-up", Icon: TrendingUp, k: "crescita aumento trend successo" },
  { key: "activity", Icon: Activity, k: "attivita monitoraggio battito" },
  { key: "calculator", Icon: Calculator, k: "calcolatrice conti matematica" },
  { key: "scale", Icon: Scale, k: "bilancia legge giustizia misura" },
  { key: "banknote", Icon: Banknote, k: "soldi contanti budget finanza" },
  { key: "wallet", Icon: Wallet, k: "portafoglio pagamenti budget" },
  { key: "credit-card", Icon: CreditCard, k: "carta pagamento credito" },
  { key: "receipt", Icon: Receipt, k: "ricevuta fattura spese contabilita" },
  { key: "coins", Icon: Coins, k: "monete soldi valuta budget" },
  { key: "euro", Icon: Euro, k: "euro valuta soldi" },
  { key: "file", Icon: File, k: "file documento" },
  { key: "file-text", Icon: FileText, k: "documento testo nota relazione" },
  { key: "notebook", Icon: Notebook, k: "quaderno appunti note" },
  { key: "book", Icon: BookOpen, k: "libro manuale documentazione guida" },
  { key: "scroll", Icon: Scroll, k: "pergamena documento storia testo" },
  { key: "clipboard", Icon: ClipboardList, k: "lista attivita todo compiti" },
  { key: "checklist", Icon: ListChecks, k: "checklist lista attivita todo" },
  { key: "table", Icon: Table2, k: "tabella foglio dati elenco" },
  { key: "grid", Icon: LayoutGrid, k: "griglia dashboard layout" },
  { key: "layers", Icon: Layers, k: "livelli strati stack" },
  { key: "sticker", Icon: Sticker, k: "adesivo etichetta sticker" },
  { key: "stamp", Icon: Stamp, k: "timbro approvazione ufficiale" },
  { key: "package", Icon: Package, k: "pacco prodotto spedizione" },
  { key: "boxes", Icon: Boxes, k: "scatole magazzino imballaggio" },
  { key: "cart", Icon: ShoppingCart, k: "carrello acquisti ecommerce" },
  { key: "bag", Icon: ShoppingBag, k: "shopping acquisti negozio" },
  { key: "truck", Icon: Truck, k: "camion spedizione logistica consegna" },
  { key: "plane", Icon: Plane, k: "aereo viaggio trasferta" },
  { key: "ship", Icon: Ship, k: "nave mare spedizione" },
  { key: "anchor", Icon: Anchor, k: "ancora stabilita nautica" },
  { key: "calendar", Icon: Calendar, k: "calendario date pianificazione eventi" },
  { key: "clock", Icon: Clock, k: "orologio tempo scadenza" },
  { key: "timer", Icon: Timer, k: "timer cronometro tempo" },
  { key: "alarm", Icon: AlarmClock, k: "sveglia promemoria scadenza" },
  { key: "bell", Icon: Bell, k: "campanella notifiche avvisi" },
  { key: "mail", Icon: Mail, k: "email posta messaggi contatti" },
  { key: "send", Icon: Send, k: "invio invia messaggio" },
  { key: "message", Icon: MessageSquare, k: "messaggi chat comunicazione" },
  { key: "phone", Icon: Phone, k: "telefono chiamata contatti" },
  { key: "users", Icon: Users, k: "utenti team gruppo persone" },
  { key: "user", Icon: User, k: "utente persona profilo cliente" },
  { key: "handshake", Icon: Handshake, k: "accordo collaborazione partnership contratto" },
  { key: "graduation", Icon: GraduationCap, k: "studio scuola formazione universita" },
  { key: "languages", Icon: Languages, k: "lingue traduzione internazionale" },
  { key: "crown", Icon: Crown, k: "corona premium vip" },
  { key: "award", Icon: Award, k: "premio riconoscimento qualita" },
  { key: "camera", Icon: Camera, k: "fotocamera foto immagini" },
  { key: "image", Icon: Image, k: "immagine foto grafica" },
  { key: "video", Icon: Video, k: "video filmato registrazione" },
  { key: "film", Icon: Film, k: "cinema film video" },
  { key: "music", Icon: Music, k: "musica audio brano" },
  { key: "mic", Icon: Mic, k: "microfono registrazione audio podcast" },
  { key: "palette", Icon: Palette, k: "colori design grafica arte" },
  { key: "brush", Icon: Brush, k: "pennello pittura arte design" },
  { key: "paintbrush", Icon: Paintbrush, k: "pennello pittura grafica" },
  { key: "pen-tool", Icon: PenTool, k: "matita design grafica vettoriale" },
  { key: "pencil", Icon: Pencil, k: "matita scrivere modifica bozza" },
  { key: "type", Icon: Type, k: "testo font tipografia" },
  { key: "scissors", Icon: Scissors, k: "forbici taglia sartoria" },
  { key: "ruler", Icon: Ruler, k: "righello misura disegno" },
  { key: "highlighter", Icon: Highlighter, k: "evidenziatore annotazione studio" },
  { key: "wrench", Icon: Wrench, k: "chiave riparazione manutenzione configurazione" },
  { key: "hammer", Icon: Hammer, k: "martello costruzione riparazione lavori" },
  { key: "settings", Icon: Settings, k: "impostazioni configurazione ingranaggi" },
  { key: "cog", Icon: Cog, k: "ingranaggio automazione impostazioni" },
  { key: "sliders", Icon: SlidersHorizontal, k: "regolazioni impostazioni filtri" },
  { key: "funnel", Icon: Funnel, k: "filtro selezione conversione" },
  { key: "search", Icon: Search, k: "ricerca cerca lente" },
  { key: "shield", Icon: Shield, k: "sicurezza protezione scudo" },
  { key: "lock", Icon: Lock, k: "lucchetto sicurezza privato" },
  { key: "key", Icon: Key, k: "chiave accesso password sicurezza" },
  { key: "zap", Icon: Zap, k: "energia velocita elettrico fulmine" },
  { key: "lightbulb", Icon: Lightbulb, k: "idea lampadina innovazione" },
  { key: "flame", Icon: Flame, k: "fuoco fiamma hot trending" },
  { key: "sparkles", Icon: Sparkles, k: "scintille novita magia brillante" },
  { key: "star", Icon: Star, k: "stella preferiti importante" },
  { key: "heart", Icon: Heart, k: "cuore preferito amore salute" },
  { key: "bookmark", Icon: Bookmark, k: "segnalibro salvato" },
  { key: "tag", Icon: Tag, k: "etichetta tag categoria" },
  { key: "gift", Icon: Gift, k: "regalo promozione offerta" },
  { key: "trophy", Icon: Trophy, k: "trofeo premio vittoria successo" },
  { key: "gem", Icon: Gem, k: "gemma diamante premium lusso" },
  { key: "party", Icon: PartyPopper, k: "festa evento celebrazione" },
  { key: "ticket", Icon: Ticket, k: "biglietto evento supporto" },
  { key: "percent", Icon: Percent, k: "percentuale sconto tasso" },
  { key: "atom", Icon: Atom, k: "atomo scienza fisica" },
  { key: "flask", Icon: FlaskConical, k: "chimica laboratorio esperimento" },
  { key: "microscope", Icon: Microscope, k: "microscopio ricerca laboratorio" },
  { key: "stethoscope", Icon: Stethoscope, k: "medicina salute dottore" },
  { key: "pill", Icon: Pill, k: "medicina farmaco salute" },
  { key: "dumbbell", Icon: Dumbbell, k: "palestra fitness allenamento" },
  { key: "bug", Icon: Bug, k: "bug insetto errore debug" },
  { key: "eye", Icon: Eye, k: "occhio visibilita osservazione" },
  { key: "coffee", Icon: Coffee, k: "caffe pausa bar" },
  { key: "utensils", Icon: Utensils, k: "ristorante cibo cucina" },
  { key: "pizza", Icon: Pizza, k: "pizza cibo ristorante" },
  { key: "cake", Icon: Cake, k: "torta compleanno dolce festa" },
  { key: "cookie", Icon: Cookie, k: "biscotto dolce web" },
  { key: "popcorn", Icon: Popcorn, k: "popcorn cinema intrattenimento" },
  { key: "apple", Icon: Apple, k: "mela frutta cibo" },
  { key: "grape", Icon: Grape, k: "uva frutta vino" },
  { key: "leaf", Icon: Leaf, k: "foglia natura eco verde" },
  { key: "sprout", Icon: Sprout, k: "germoglio crescita natura" },
  { key: "trees", Icon: Trees, k: "alberi natura bosco eco" },
  { key: "flower", Icon: Flower2, k: "fiore giardino primavera" },
  { key: "sun", Icon: Sun, k: "sole giorno luce estate" },
  { key: "moon", Icon: Moon, k: "luna notte dark" },
  { key: "cloud-rain", Icon: CloudRain, k: "pioggia meteo clima" },
  { key: "snowflake", Icon: Snowflake, k: "neve inverno freddo" },
  { key: "mountain", Icon: Mountain, k: "montagna natura trekking" },
  { key: "dog", Icon: Dog, k: "cane animale pet" },
  { key: "cat", Icon: Cat, k: "gatto animale pet" },
  { key: "bird", Icon: Bird, k: "uccello animale volare" },
  { key: "fish", Icon: Fish, k: "pesce mare animale" },
  { key: "rabbit", Icon: Rabbit, k: "coniglio animale pet" },
  { key: "paw", Icon: PawPrint, k: "zampa animale pet" },
  { key: "monitor", Icon: Monitor, k: "monitor schermo desktop pc" },
  { key: "laptop", Icon: Laptop, k: "laptop computer portatile" },
  { key: "smartphone", Icon: Smartphone, k: "smartphone telefono mobile app" },
  { key: "tv", Icon: Tv, k: "tv televisione schermo" },
  { key: "printer", Icon: Printer, k: "stampante stampa" },
  { key: "keyboard", Icon: Keyboard, k: "tastiera input" },
  { key: "watch", Icon: Watch, k: "orologio tempo indossabile" },
  { key: "gamepad", Icon: Gamepad2, k: "gioco videogame gaming" },
  { key: "puzzle", Icon: Puzzle, k: "puzzle problem solving integrazione" },
  { key: "blocks", Icon: Blocks, k: "blocchi componenti modulare" },
  { key: "hash", Icon: Hash, k: "cancelletto hashtag numero" },
  { key: "at", Icon: AtSign, k: "chiocciola email menzione" },
  { key: "map", Icon: MapIcon, k: "mappa geografia viaggio" },
  { key: "map-pin", Icon: MapPin, k: "luogo posizione indirizzo sede" },
  { key: "compass", Icon: Compass, k: "bussola direzione orientamento" },
];

const ICON_MAP = new Map(PROJECT_ICONS.map((e) => [e.key, e.Icon]));

/**
 * Restituisce il componente icona lucide per una chiave.
 * Se la chiave non esiste, ritorna l'icona di default.
 */
export const getProjectIcon = (key) =>
  ICON_MAP.get(key) || ICON_MAP.get(DEFAULT_PROJECT_ICON);

/**
 * True se la chiave è tra le icone "preferite" incluse nel bundle
 * (possono essere renderizzate subito, senza CDN).
 */
export const hasStaticIcon = (key) => ICON_MAP.has(key);
